services:
  postgres:
    image: postgres:18
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data

volumes:
  pgdata: